title: Courtney K. Allen # your name (or website title) here
logo: "/images/Profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD Student <br>
  Social demographer <br> 
  <br><br>
  <a href="https://www.linkedin.com/in/courtney-allen/">LinkedIn </a> 
  <br><br>
  <a href="/pdf/Allen_CV_202212.pdf">See my CV</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-26401120 # your Google Analytics tracking ID here
