title: Courtney K. Allen # your name (or website title) here
logo: "/images/headshot.jpg?raw=true" # your photo (or logo) here
description:
  PhD Candidate <br>
  University of Washington <br>
  Social demographer <br>
  <br><br>
  <a href="https://www.linkedin.com/in/courtney-allen/">LinkedIn </a> 
  <a href="/pdf/Allen_CV_202504.pdf">See my CV</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal 

author:
  employer         : "University of Washington"
  uri              : courtneykirsten@github.io
  email            : "ckallen@uw.edu" 
  googlescholar    : "https://scholar.google.com/citations?user=aYf2JaEAAAAJ&hl=en"
